version: '3'

services:
  backend:
    build: ./back
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./front
    ports:
      - "80:3000"
    restart: unless-stopped
    depends_on:
      - backend